apiVersion: v1
kind: Service
metadata:
  name: orka-admission
  namespace: orka-system
  labels:
    app.kubernetes.io/name: orka
    app.kubernetes.io/component: admission
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app.kubernetes.io/name: orka
    app.kubernetes.io/component: admission
  ports:
    - name: https
      port: 443
      targetPort: webhook
      protocol: TCP
