apiVersion: v1
kind: ServiceAccount
metadata:
  name: orka-admission
  namespace: orka-system
  labels:
    app.kubernetes.io/name: orka
    app.kubernetes.io/component: admission
    app.kubernetes.io/managed-by: kustomize
automountServiceAccountToken: true
