version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      kubernetes:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
      opentelemetry:
        patterns:
          - "go.opentelemetry.io/*"
      prometheus:
        patterns:
          - "github.com/prometheus/*"
      golang:
        patterns:
          - "golang.org/x/*"
      testing:
        patterns:
          - "github.com/onsi/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/workers/ai"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/workers/general"
    schedule:
      interval: "weekly"
