apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: orka-system
namePrefix: orka-
configurations:
  - kustomizeconfig.yaml
resources:
  - ../rbac
  - ../manager
  - ../publisher
  - ../provider-proxy
  - ../scm-egress-proxy
  - ../admission
  - ../policy
  - metrics_service.yaml
  - api_service.yaml
patches:
  - path: manager_metrics_patch.yaml
    target:
      kind: Deployment
      name: controller-manager
replacements:
- source:
    group: ""
    version: v1
    kind: Namespace
    name: system
    fieldPath: metadata.name
  targets:
  - select:
      group: admissionregistration.k8s.io
      version: v1
      kind: ValidatingAdmissionPolicy
      name: gateway-task-protection
    fieldPaths:
    - spec.variables.[name=controllerNamespace].expression
    options:
      delimiter: "'"
      index: 1
- source:
    group: ""
    version: v1
    kind: ServiceAccount
    name: controller-manager
    fieldPath: metadata.name
  targets:
  - select:
      group: admissionregistration.k8s.io
      version: v1
      kind: ValidatingAdmissionPolicy
      name: gateway-task-protection
    fieldPaths:
    - spec.variables.[name=controllerServiceAccount].expression
    options:
      delimiter: "'"
      index: 1
- source:
    group: ""
    version: v1
    kind: ServiceAccount
    name: ai-worker
    fieldPath: metadata.name
  targets:
  - select:
      group: admissionregistration.k8s.io
      version: v1
      kind: ValidatingAdmissionPolicy
      name: gateway-task-protection
    fieldPaths:
    - spec.variables.[name=aiWorkerServiceAccount].expression
    options:
      delimiter: "'"
      index: 1
- source:
    group: ""
    version: v1
    kind: ServiceAccount
    name: vendor-worker
    fieldPath: metadata.name
  targets:
  - select:
      group: admissionregistration.k8s.io
      version: v1
      kind: ValidatingAdmissionPolicy
      name: gateway-task-protection
    fieldPaths:
    - spec.variables.[name=vendorWorkerServiceAccount].expression
    options:
      delimiter: "'"
      index: 1
- source:
    group: ""
    version: v1
    kind: ServiceAccount
    name: container-worker
    fieldPath: metadata.name
  targets:
  - select:
      group: admissionregistration.k8s.io
      version: v1
      kind: ValidatingAdmissionPolicy
      name: gateway-task-protection
    fieldPaths:
    - spec.variables.[name=containerWorkerServiceAccount].expression
    options:
      delimiter: "'"
      index: 1

transformers:
- remove_admission_policy_namespace.yaml
- remove_admission_policy_binding_namespace.yaml
