resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- newName: ghcr.io/sozercan/orka
  newTag: latest
- name: controller
  newName: docker.io/sozercan/orka-controller
  newTag: latest
