resources:
- manager.yaml
- store-pvc.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- newName: ghcr.io/orka-agents/orka
  newTag: 0.1.1
- name: controller
  newName: ghcr.io/orka-agents/orka
  newTag: 0.1.1
