/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as SecurityIndexRouteImport } from './routes/security/index'
import { Route as MonitorsIndexRouteImport } from './routes/monitors/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as ToolsToolNameRouteImport } from './routes/tools/$toolName'
import { Route as TasksNewRouteImport } from './routes/tasks/new'
import { Route as TasksTaskIdRouteImport } from './routes/tasks/$taskId'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as SecurityNewRouteImport } from './routes/security/new'
import { Route as SecurityRepoIdRouteImport } from './routes/security/$repoId'
import { Route as MonitorsMonitorIdRouteImport } from './routes/monitors/$monitorId'
import { Route as AgentsNewRouteImport } from './routes/agents/new'
import { Route as AgentsAgentIdRouteImport } from './routes/agents/$agentId'
import { Route as SecurityFindingsFindingIdRouteImport } from './routes/security/findings/$findingId'
import { Route as MonitorsCreateNewRouteImport } from './routes/monitors/create/new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityIndexRoute = SecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorsIndexRoute = MonitorsIndexRouteImport.update({
  id: '/monitors/',
  path: '/monitors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsToolNameRoute = ToolsToolNameRouteImport.update({
  id: '/tools/$toolName',
  path: '/tools/$toolName',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksNewRoute = TasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityNewRoute = SecurityNewRouteImport.update({
  id: '/security/new',
  path: '/security/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRepoIdRoute = SecurityRepoIdRouteImport.update({
  id: '/security/$repoId',
  path: '/security/$repoId',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorsMonitorIdRoute = MonitorsMonitorIdRouteImport.update({
  id: '/monitors/$monitorId',
  path: '/monitors/$monitorId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityFindingsFindingIdRoute =
  SecurityFindingsFindingIdRouteImport.update({
    id: '/security/findings/$findingId',
    path: '/security/findings/$findingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MonitorsCreateNewRoute = MonitorsCreateNewRouteImport.update({
  id: '/monitors/create/new',
  path: '/monitors/create/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/kanban': typeof KanbanRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/monitors/$monitorId': typeof MonitorsMonitorIdRoute
  '/security/$repoId': typeof SecurityRepoIdRoute
  '/security/new': typeof SecurityNewRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/tools/$toolName': typeof ToolsToolNameRoute
  '/agents/': typeof AgentsIndexRoute
  '/monitors/': typeof MonitorsIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/monitors/create/new': typeof MonitorsCreateNewRoute
  '/security/findings/$findingId': typeof SecurityFindingsFindingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/kanban': typeof KanbanRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/monitors/$monitorId': typeof MonitorsMonitorIdRoute
  '/security/$repoId': typeof SecurityRepoIdRoute
  '/security/new': typeof SecurityNewRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/tools/$toolName': typeof ToolsToolNameRoute
  '/agents': typeof AgentsIndexRoute
  '/monitors': typeof MonitorsIndexRoute
  '/security': typeof SecurityIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/monitors/create/new': typeof MonitorsCreateNewRoute
  '/security/findings/$findingId': typeof SecurityFindingsFindingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/kanban': typeof KanbanRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/agents/new': typeof AgentsNewRoute
  '/monitors/$monitorId': typeof MonitorsMonitorIdRoute
  '/security/$repoId': typeof SecurityRepoIdRoute
  '/security/new': typeof SecurityNewRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/tasks/new': typeof TasksNewRoute
  '/tools/$toolName': typeof ToolsToolNameRoute
  '/agents/': typeof AgentsIndexRoute
  '/monitors/': typeof MonitorsIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/monitors/create/new': typeof MonitorsCreateNewRoute
  '/security/findings/$findingId': typeof SecurityFindingsFindingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/kanban'
    | '/live'
    | '/login'
    | '/agents/$agentId'
    | '/agents/new'
    | '/monitors/$monitorId'
    | '/security/$repoId'
    | '/security/new'
    | '/sessions/$sessionId'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/tools/$toolName'
    | '/agents/'
    | '/monitors/'
    | '/security/'
    | '/sessions/'
    | '/tasks/'
    | '/tools/'
    | '/monitors/create/new'
    | '/security/findings/$findingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/kanban'
    | '/live'
    | '/login'
    | '/agents/$agentId'
    | '/agents/new'
    | '/monitors/$monitorId'
    | '/security/$repoId'
    | '/security/new'
    | '/sessions/$sessionId'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/tools/$toolName'
    | '/agents'
    | '/monitors'
    | '/security'
    | '/sessions'
    | '/tasks'
    | '/tools'
    | '/monitors/create/new'
    | '/security/findings/$findingId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/kanban'
    | '/live'
    | '/login'
    | '/agents/$agentId'
    | '/agents/new'
    | '/monitors/$monitorId'
    | '/security/$repoId'
    | '/security/new'
    | '/sessions/$sessionId'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/tools/$toolName'
    | '/agents/'
    | '/monitors/'
    | '/security/'
    | '/sessions/'
    | '/tasks/'
    | '/tools/'
    | '/monitors/create/new'
    | '/security/findings/$findingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  KanbanRoute: typeof KanbanRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  AgentsNewRoute: typeof AgentsNewRoute
  MonitorsMonitorIdRoute: typeof MonitorsMonitorIdRoute
  SecurityRepoIdRoute: typeof SecurityRepoIdRoute
  SecurityNewRoute: typeof SecurityNewRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  TasksNewRoute: typeof TasksNewRoute
  ToolsToolNameRoute: typeof ToolsToolNameRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  MonitorsIndexRoute: typeof MonitorsIndexRoute
  SecurityIndexRoute: typeof SecurityIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  MonitorsCreateNewRoute: typeof MonitorsCreateNewRoute
  SecurityFindingsFindingIdRoute: typeof SecurityFindingsFindingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/': {
      id: '/security/'
      path: '/security'
      fullPath: '/security/'
      preLoaderRoute: typeof SecurityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitors/': {
      id: '/monitors/'
      path: '/monitors'
      fullPath: '/monitors/'
      preLoaderRoute: typeof MonitorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$toolName': {
      id: '/tools/$toolName'
      path: '/tools/$toolName'
      fullPath: '/tools/$toolName'
      preLoaderRoute: typeof ToolsToolNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/new': {
      id: '/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof TasksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/new': {
      id: '/security/new'
      path: '/security/new'
      fullPath: '/security/new'
      preLoaderRoute: typeof SecurityNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/$repoId': {
      id: '/security/$repoId'
      path: '/security/$repoId'
      fullPath: '/security/$repoId'
      preLoaderRoute: typeof SecurityRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitors/$monitorId': {
      id: '/monitors/$monitorId'
      path: '/monitors/$monitorId'
      fullPath: '/monitors/$monitorId'
      preLoaderRoute: typeof MonitorsMonitorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/findings/$findingId': {
      id: '/security/findings/$findingId'
      path: '/security/findings/$findingId'
      fullPath: '/security/findings/$findingId'
      preLoaderRoute: typeof SecurityFindingsFindingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitors/create/new': {
      id: '/monitors/create/new'
      path: '/monitors/create/new'
      fullPath: '/monitors/create/new'
      preLoaderRoute: typeof MonitorsCreateNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  KanbanRoute: KanbanRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  AgentsNewRoute: AgentsNewRoute,
  MonitorsMonitorIdRoute: MonitorsMonitorIdRoute,
  SecurityRepoIdRoute: SecurityRepoIdRoute,
  SecurityNewRoute: SecurityNewRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  TasksNewRoute: TasksNewRoute,
  ToolsToolNameRoute: ToolsToolNameRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  MonitorsIndexRoute: MonitorsIndexRoute,
  SecurityIndexRoute: SecurityIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  MonitorsCreateNewRoute: MonitorsCreateNewRoute,
  SecurityFindingsFindingIdRoute: SecurityFindingsFindingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
