{{- if not .Values.workers.harnessWrapper.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orka.fullname" . }}-harness-wrapper-auth
  labels:
    {{- include "orka.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent-harness-wrapper
type: Opaque
stringData:
  {{ .Values.workers.harnessWrapper.auth.tokenKey | default "token" }}: {{ .Values.workers.harnessWrapper.auth.token | quote }}
{{- end }}
