package controller

import (
	"context"
	"errors"
	"fmt"
	"strings"

	apiequality "k8s.io/apimachinery/pkg/api/equality"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"

	corev1alpha1 "github.com/orka-agents/orka/api/v1alpha1"
	"github.com/orka-agents/orka/internal/labels"
	"github.com/orka-agents/orka/internal/security"
	"github.com/orka-agents/orka/internal/store"
)

func repositoryScanControlsTask(scan *corev1alpha1.RepositoryScan, task *corev1alpha1.Task) bool {
	if scan == nil || task == nil {
		return false
	}
	if scan.UID == "" {
		// Fake clients and pre-UID legacy fixtures cannot express an exact owner
		// binding. Production RepositoryScans always have a UID; only preserve
		// label-scoped compatibility for that explicitly unverifiable state.
		return task.Labels[labels.LabelSecurityTarget] == labels.SelectorValue(scan.Name)
	}
	return metav1.IsControlledBy(task, scan)
}

func threatModelMatchesRepositoryScan(
	model *store.ThreatModel,
	scan *corev1alpha1.RepositoryScan,
) bool {
	if model == nil || scan == nil || model.RepositoryScan != scan.Name {
		return false
	}
	if scan.UID == "" {
		return true
	}
	return model.RepositoryScanUID != "" && model.RepositoryScanGeneration > 0 &&
		model.RepositoryScanUID == string(scan.UID) && model.RepositoryScanGeneration == scan.Generation
}

func repositoryScanControlledTasks(
	scan *corev1alpha1.RepositoryScan,
	tasks []corev1alpha1.Task,
) []corev1alpha1.Task {
	controlled := make([]corev1alpha1.Task, 0, len(tasks))
	for i := range tasks {
		if repositoryScanControlsTask(scan, &tasks[i]) {
			controlled = append(controlled, tasks[i])
		}
	}
	return controlled
}

func (r *RepositoryScanReconciler) createOrValidateSecurityTask(
	ctx context.Context,
	scan *corev1alpha1.RepositoryScan,
	expected *corev1alpha1.Task,
) error {
	if scan == nil || expected == nil {
		return fmt.Errorf("repository scan and expected task are required")
	}
	if err := r.Create(ctx, expected); err == nil {
		return nil
	} else if !apierrors.IsAlreadyExists(err) {
		return err
	}

	existing := &corev1alpha1.Task{}
	if err := r.Get(ctx, types.NamespacedName{Namespace: expected.Namespace, Name: expected.Name}, existing); err != nil {
		return err
	}
	if !repositoryScanControlsTask(scan, existing) {
		return fmt.Errorf("existing security task %s/%s is not controlled by RepositoryScan UID %s", existing.Namespace, existing.Name, scan.UID)
	}
	for key, value := range expected.Labels {
		if existing.Labels[key] != value {
			return fmt.Errorf("existing security task %s/%s label %s does not match expected run binding", existing.Namespace, existing.Name, key)
		}
	}
	for key, value := range expected.Annotations {
		if existing.Annotations[key] != value {
			return fmt.Errorf("existing security task %s/%s annotation %s does not match expected execution binding", existing.Namespace, existing.Name, key)
		}
	}
	for key, value := range existing.Labels {
		if !securityTaskProtectedMetadataKey(key) {
			continue
		}
		if expectedValue, ok := expected.Labels[key]; !ok || expectedValue != value {
			return fmt.Errorf("existing security task %s/%s has unexpected protected label %s", existing.Namespace, existing.Name, key)
		}
	}
	for key, value := range existing.Annotations {
		if !securityTaskProtectedMetadataKey(key) {
			continue
		}
		if expectedValue, ok := expected.Annotations[key]; !ok || expectedValue != value {
			return fmt.Errorf("existing security task %s/%s has unexpected protected annotation %s", existing.Namespace, existing.Name, key)
		}
	}
	if !apiequality.Semantic.DeepEqual(existing.Spec, expected.Spec) {
		return fmt.Errorf("existing security task %s/%s spec does not match expected run binding", existing.Namespace, existing.Name)
	}
	return nil
}

func securityTaskProtectedMetadataKey(key string) bool {
	return strings.HasPrefix(key, "orka.ai/security-") || strings.HasPrefix(key, "orka.ai/harness-wrapper-")
}

func (r *RepositoryScanReconciler) immutableRunThreatModel(
	ctx context.Context,
	run *store.ScanRun,
) (string, error) {
	if run == nil {
		return "", fmt.Errorf("immutable run threat model requires a bound scan run")
	}
	if run.RunUID == "" {
		// Legacy runs predate immutable run snapshots. They remain explicitly
		// unverified and may continue with only a model generated by that same
		// public run; edited/latest content is never substituted.
		if r.SecurityStore == nil {
			return "", nil
		}
		model, err := r.SecurityStore.GetLatestThreatModel(ctx, run.Namespace, run.RepositoryScan)
		if errors.Is(err, store.ErrNotFound) {
			return "", nil
		}
		if err != nil {
			return "", err
		}
		if model.GeneratedByScan != run.ID {
			return "", nil
		}
		return strings.TrimSpace(model.Content), nil
	}
	if !security.ValidRunUID(run.RunUID) {
		return "", fmt.Errorf("immutable run threat model requires a valid non-empty run UID")
	}
	runThreatModelStore := r.RunThreatModelStore
	if runThreatModelStore == nil {
		if compatible, ok := r.SecurityStore.(store.SecurityRunThreatModelStore); ok {
			runThreatModelStore = compatible
		}
	}
	if runThreatModelStore == nil {
		return "", fmt.Errorf("immutable run threat-model store is unavailable")
	}
	model, err := runThreatModelStore.GetSecurityRunThreatModel(ctx, run.Namespace, run.RunUID)
	if err != nil {
		return "", fmt.Errorf("load immutable run threat model: %w", err)
	}
	if model.RunUID != run.RunUID || model.Namespace != run.Namespace ||
		model.RepositoryScan != run.RepositoryScan || model.ScanRunID != run.ID {
		return "", fmt.Errorf("immutable run threat model binding does not match scan run")
	}
	content := strings.TrimSpace(model.Content)
	if content == "" {
		return "", fmt.Errorf("immutable run threat model content is empty")
	}
	return content, nil
}
