apiVersion: v1
kind: Secret
metadata:
  name: fibey-http-runtime-token
  annotations:
    orka.ai/agent-runtime-endpoint: http://fibey-http-runtime.default.svc.cluster.local:8080
  labels:
    orka.ai/agent-runtime-auth: "true"
    orka.ai/agent-runtime-name: fibey-http-runtime
stringData:
  token: mock-token
