apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: orka
    app.kubernetes.io/managed-by: kustomize
  name: workspace-provider-config-reader
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      workspace.orka.ai/aggregate-to-provider-config-reader: "true"
rules: []
