apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: orka
    app.kubernetes.io/managed-by: kustomize
  name: workspace-provider-config-reader-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workspace-provider-config-reader
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
