apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-publisher
  labels:
    app.kubernetes.io/name: orka
    app.kubernetes.io/component: workspace-publisher
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
