apiVersion: v1
kind: ServiceAccount
metadata:
  name: workspace-publisher
  labels:
    app.kubernetes.io/name: orka
    app.kubernetes.io/component: workspace-publisher
automountServiceAccountToken: false
