{{- if .Values.store.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mercan.fullname" . }}-store
  labels:
    {{- include "mercan.labels" . | nindent 4 }}
    app.kubernetes.io/component: store
spec:
  accessModes:
    - {{ .Values.store.persistence.accessMode }}
  {{- if .Values.store.persistence.storageClass }}
  storageClassName: {{ .Values.store.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.store.persistence.size }}
{{- end }}
