apiVersion: core.orka.ai/v1alpha1
kind: Tool
metadata:
  labels:
    app.kubernetes.io/name: orka
    app.kubernetes.io/managed-by: kustomize
  name: tool-sample
spec:
  # TODO(user): Add fields here
