## Append samples of your project ##
resources:
- core_v1alpha1_task.yaml
- core_v1alpha1_task_agent.yaml
- core_v1alpha1_task_agent_copilot.yaml
- core_v1alpha1_task_agent_workspace.yaml
- core_v1alpha1_tool.yaml
- core_v1alpha1_agent.yaml
- core_v1alpha1_agentruntime.yaml
- core_v1alpha1_agentruntime_agentkit.yaml
- core_v1alpha1_agentruntime_foundry.yaml
- core_v1alpha1_agent_claude.yaml
- core_v1alpha1_agent_codex.yaml
- core_v1alpha1_agent_opencode.yaml
- gateway_v1alpha1_gatewayclass.yaml
- gateway_v1alpha1_gateway.yaml
- gateway_v1alpha1_gatewaybinding.yaml
- workspace_v1alpha1_executionworkspaceprovider.yaml
- workspace_v1alpha1_executionworkspacepool.yaml
- workspace_v1alpha1_executionworkspaceclass.yaml
- workspace_v1alpha1_executionworkspace.yaml
- fake.workspace_v1alpha1_fakeproviderconfig.yaml
- fake.workspace_v1alpha1_fakepoolparameters.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
