//go:build !ignore_autogenerated

/*
Copyright (c) 2026.

MIT License - see LICENSE file for details.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AISpec) DeepCopyInto(out *AISpec) {
	*out = *in
	if in.ProviderRef != nil {
		in, out := &in.ProviderRef, &out.ProviderRef
		*out = new(ProviderReference)
		**out = **in
	}
	if in.Temperature != nil {
		in, out := &in.Temperature, &out.Temperature
		*out = new(float64)
		**out = **in
	}
	if in.MaxTokens != nil {
		in, out := &in.MaxTokens, &out.MaxTokens
		*out = new(int32)
		**out = **in
	}
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = make([]SkillReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AISpec.
func (in *AISpec) DeepCopy() *AISpec {
	if in == nil {
		return nil
	}
	out := new(AISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Agent) DeepCopyInto(out *Agent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Agent.
func (in *Agent) DeepCopy() *Agent {
	if in == nil {
		return nil
	}
	out := new(Agent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Agent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCLIRuntime) DeepCopyInto(out *AgentCLIRuntime) {
	*out = *in
	if in.DefaultMaxTurns != nil {
		in, out := &in.DefaultMaxTurns, &out.DefaultMaxTurns
		*out = new(int32)
		**out = **in
	}
	if in.DefaultAllowedTools != nil {
		in, out := &in.DefaultAllowedTools, &out.DefaultAllowedTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultAllowBash != nil {
		in, out := &in.DefaultAllowBash, &out.DefaultAllowBash
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCLIRuntime.
func (in *AgentCLIRuntime) DeepCopy() *AgentCLIRuntime {
	if in == nil {
		return nil
	}
	out := new(AgentCLIRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentList) DeepCopyInto(out *AgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Agent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentList.
func (in *AgentList) DeepCopy() *AgentList {
	if in == nil {
		return nil
	}
	out := new(AgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentReference) DeepCopyInto(out *AgentReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentReference.
func (in *AgentReference) DeepCopy() *AgentReference {
	if in == nil {
		return nil
	}
	out := new(AgentReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRuntimeSpec) DeepCopyInto(out *AgentRuntimeSpec) {
	*out = *in
	if in.Workspace != nil {
		in, out := &in.Workspace, &out.Workspace
		*out = new(WorkspaceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxTurns != nil {
		in, out := &in.MaxTurns, &out.MaxTurns
		*out = new(int32)
		**out = **in
	}
	if in.AllowedTools != nil {
		in, out := &in.AllowedTools, &out.AllowedTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DisallowedTools != nil {
		in, out := &in.DisallowedTools, &out.DisallowedTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowBash != nil {
		in, out := &in.AllowBash, &out.AllowBash
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRuntimeSpec.
func (in *AgentRuntimeSpec) DeepCopy() *AgentRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	if in.ProviderRef != nil {
		in, out := &in.ProviderRef, &out.ProviderRef
		*out = new(ProviderReference)
		**out = **in
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(ModelConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SystemPrompt != nil {
		in, out := &in.SystemPrompt, &out.SystemPrompt
		*out = new(PromptSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Tools != nil {
		in, out := &in.Tools, &out.Tools
		*out = make([]ToolReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = make([]SkillReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Execution != nil {
		in, out := &in.Execution, &out.Execution
		*out = new(ExecutionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.Session != nil {
		in, out := &in.Session, &out.Session
		*out = new(SessionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(RateLimitConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Coordination != nil {
		in, out := &in.Coordination, &out.Coordination
		*out = new(CoordinationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(AgentCLIRuntime)
		(*in).DeepCopyInto(*out)
	}
	if in.TTLAfterLastTask != nil {
		in, out := &in.TTLAfterLastTask, &out.TTLAfterLastTask
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentStatus) DeepCopyInto(out *AgentStatus) {
	*out = *in
	if in.LastUsed != nil {
		in, out := &in.LastUsed, &out.LastUsed
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentStatus.
func (in *AgentStatus) DeepCopy() *AgentStatus {
	if in == nil {
		return nil
	}
	out := new(AgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedAgent) DeepCopyInto(out *AllowedAgent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedAgent.
func (in *AllowedAgent) DeepCopy() *AllowedAgent {
	if in == nil {
		return nil
	}
	out := new(AllowedAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureConfig) DeepCopyInto(out *AzureConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureConfig.
func (in *AzureConfig) DeepCopy() *AzureConfig {
	if in == nil {
		return nil
	}
	out := new(AzureConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChildTaskStatus) DeepCopyInto(out *ChildTaskStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChildTaskStatus.
func (in *ChildTaskStatus) DeepCopy() *ChildTaskStatus {
	if in == nil {
		return nil
	}
	out := new(ChildTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapKeySelector) DeepCopyInto(out *ConfigMapKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapKeySelector.
func (in *ConfigMapKeySelector) DeepCopy() *ConfigMapKeySelector {
	if in == nil {
		return nil
	}
	out := new(ConfigMapKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoordinationConfig) DeepCopyInto(out *CoordinationConfig) {
	*out = *in
	if in.AllowedAgents != nil {
		in, out := &in.AllowedAgents, &out.AllowedAgents
		*out = make([]AllowedAgent, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoordinationConfig.
func (in *CoordinationConfig) DeepCopy() *CoordinationConfig {
	if in == nil {
		return nil
	}
	out := new(CoordinationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionSpec) DeepCopyInto(out *ExecutionSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Workspace != nil {
		in, out := &in.Workspace, &out.Workspace
		*out = new(ExecutionWorkspaceSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionSpec.
func (in *ExecutionSpec) DeepCopy() *ExecutionSpec {
	if in == nil {
		return nil
	}
	out := new(ExecutionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionWorkspaceDensityStatus) DeepCopyInto(out *ExecutionWorkspaceDensityStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionWorkspaceDensityStatus.
func (in *ExecutionWorkspaceDensityStatus) DeepCopy() *ExecutionWorkspaceDensityStatus {
	if in == nil {
		return nil
	}
	out := new(ExecutionWorkspaceDensityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionWorkspaceHibernationSpec) DeepCopyInto(out *ExecutionWorkspaceHibernationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionWorkspaceHibernationSpec.
func (in *ExecutionWorkspaceHibernationSpec) DeepCopy() *ExecutionWorkspaceHibernationSpec {
	if in == nil {
		return nil
	}
	out := new(ExecutionWorkspaceHibernationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionWorkspacePlacementStatus) DeepCopyInto(out *ExecutionWorkspacePlacementStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionWorkspacePlacementStatus.
func (in *ExecutionWorkspacePlacementStatus) DeepCopy() *ExecutionWorkspacePlacementStatus {
	if in == nil {
		return nil
	}
	out := new(ExecutionWorkspacePlacementStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionWorkspaceSnapshotSpec) DeepCopyInto(out *ExecutionWorkspaceSnapshotSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionWorkspaceSnapshotSpec.
func (in *ExecutionWorkspaceSnapshotSpec) DeepCopy() *ExecutionWorkspaceSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(ExecutionWorkspaceSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionWorkspaceSpec) DeepCopyInto(out *ExecutionWorkspaceSpec) {
	*out = *in
	if in.TemplateRef != nil {
		in, out := &in.TemplateRef, &out.TemplateRef
		*out = new(WorkspaceTemplateReference)
		**out = **in
	}
	if in.PoolRef != nil {
		in, out := &in.PoolRef, &out.PoolRef
		*out = new(SubstrateActorPoolReference)
		**out = **in
	}
	if in.Snapshot != nil {
		in, out := &in.Snapshot, &out.Snapshot
		*out = new(ExecutionWorkspaceSnapshotSpec)
		**out = **in
	}
	if in.Hibernation != nil {
		in, out := &in.Hibernation, &out.Hibernation
		*out = new(ExecutionWorkspaceHibernationSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionWorkspaceSpec.
func (in *ExecutionWorkspaceSpec) DeepCopy() *ExecutionWorkspaceSpec {
	if in == nil {
		return nil
	}
	out := new(ExecutionWorkspaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionWorkspaceStatus) DeepCopyInto(out *ExecutionWorkspaceStatus) {
	*out = *in
	if in.TemplateRef != nil {
		in, out := &in.TemplateRef, &out.TemplateRef
		*out = new(WorkspaceTemplateReference)
		**out = **in
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(ExecutionWorkspacePlacementStatus)
		**out = **in
	}
	if in.Density != nil {
		in, out := &in.Density, &out.Density
		*out = new(ExecutionWorkspaceDensityStatus)
		**out = **in
	}
	if in.ResumeLatency != nil {
		in, out := &in.ResumeLatency, &out.ResumeLatency
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionWorkspaceStatus.
func (in *ExecutionWorkspaceStatus) DeepCopy() *ExecutionWorkspaceStatus {
	if in == nil {
		return nil
	}
	out := new(ExecutionWorkspaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FindingCountsStatus) DeepCopyInto(out *FindingCountsStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FindingCountsStatus.
func (in *FindingCountsStatus) DeepCopy() *FindingCountsStatus {
	if in == nil {
		return nil
	}
	out := new(FindingCountsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPExecution) DeepCopyInto(out *HTTPExecution) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.AuthSecretRef != nil {
		in, out := &in.AuthSecretRef, &out.AuthSecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPExecution.
func (in *HTTPExecution) DeepCopy() *HTTPExecution {
	if in == nil {
		return nil
	}
	out := new(HTTPExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPToolServer) DeepCopyInto(out *MCPToolServer) {
	*out = *in
	if in.SubstrateActor != nil {
		in, out := &in.SubstrateActor, &out.SubstrateActor
		*out = new(SubstrateMCPActor)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPToolServer.
func (in *MCPToolServer) DeepCopy() *MCPToolServer {
	if in == nil {
		return nil
	}
	out := new(MCPToolServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelConfig) DeepCopyInto(out *ModelConfig) {
	*out = *in
	if in.Temperature != nil {
		in, out := &in.Temperature, &out.Temperature
		*out = new(float64)
		**out = **in
	}
	if in.MaxTokens != nil {
		in, out := &in.MaxTokens, &out.MaxTokens
		*out = new(int32)
		**out = **in
	}
	if in.Fallbacks != nil {
		in, out := &in.Fallbacks, &out.Fallbacks
		*out = make([]ModelFallback, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelConfig.
func (in *ModelConfig) DeepCopy() *ModelConfig {
	if in == nil {
		return nil
	}
	out := new(ModelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelFallback) DeepCopyInto(out *ModelFallback) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelFallback.
func (in *ModelFallback) DeepCopy() *ModelFallback {
	if in == nil {
		return nil
	}
	out := new(ModelFallback)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriorTaskReference) DeepCopyInto(out *PriorTaskReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriorTaskReference.
func (in *PriorTaskReference) DeepCopy() *PriorTaskReference {
	if in == nil {
		return nil
	}
	out := new(PriorTaskReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptSource) DeepCopyInto(out *PromptSource) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(ConfigMapKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptSource.
func (in *PromptSource) DeepCopy() *PromptSource {
	if in == nil {
		return nil
	}
	out := new(PromptSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Provider) DeepCopyInto(out *Provider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Provider.
func (in *Provider) DeepCopy() *Provider {
	if in == nil {
		return nil
	}
	out := new(Provider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Provider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderList) DeepCopyInto(out *ProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Provider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderList.
func (in *ProviderList) DeepCopy() *ProviderList {
	if in == nil {
		return nil
	}
	out := new(ProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderRateLimit) DeepCopyInto(out *ProviderRateLimit) {
	*out = *in
	if in.RequestsPerMinute != nil {
		in, out := &in.RequestsPerMinute, &out.RequestsPerMinute
		*out = new(int32)
		**out = **in
	}
	if in.TokensPerMinute != nil {
		in, out := &in.TokensPerMinute, &out.TokensPerMinute
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderRateLimit.
func (in *ProviderRateLimit) DeepCopy() *ProviderRateLimit {
	if in == nil {
		return nil
	}
	out := new(ProviderRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderReference) DeepCopyInto(out *ProviderReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderReference.
func (in *ProviderReference) DeepCopy() *ProviderReference {
	if in == nil {
		return nil
	}
	out := new(ProviderReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSecretRef) DeepCopyInto(out *ProviderSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSecretRef.
func (in *ProviderSecretRef) DeepCopy() *ProviderSecretRef {
	if in == nil {
		return nil
	}
	out := new(ProviderSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSpec) DeepCopyInto(out *ProviderSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(ProviderRateLimit)
		(*in).DeepCopyInto(*out)
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(AzureConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSpec.
func (in *ProviderSpec) DeepCopy() *ProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderStatus) DeepCopyInto(out *ProviderStatus) {
	*out = *in
	if in.LastValidated != nil {
		in, out := &in.LastValidated, &out.LastValidated
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderStatus.
func (in *ProviderStatus) DeepCopy() *ProviderStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitConfig) DeepCopyInto(out *RateLimitConfig) {
	*out = *in
	if in.RequestsPerMinute != nil {
		in, out := &in.RequestsPerMinute, &out.RequestsPerMinute
		*out = new(int32)
		**out = **in
	}
	if in.TokensPerMinute != nil {
		in, out := &in.TokensPerMinute, &out.TokensPerMinute
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitConfig.
func (in *RateLimitConfig) DeepCopy() *RateLimitConfig {
	if in == nil {
		return nil
	}
	out := new(RateLimitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMonitor) DeepCopyInto(out *RepositoryMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMonitor.
func (in *RepositoryMonitor) DeepCopy() *RepositoryMonitor {
	if in == nil {
		return nil
	}
	out := new(RepositoryMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMonitorAdvisoryLabels) DeepCopyInto(out *RepositoryMonitorAdvisoryLabels) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMonitorAdvisoryLabels.
func (in *RepositoryMonitorAdvisoryLabels) DeepCopy() *RepositoryMonitorAdvisoryLabels {
	if in == nil {
		return nil
	}
	out := new(RepositoryMonitorAdvisoryLabels)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMonitorAgents) DeepCopyInto(out *RepositoryMonitorAgents) {
	*out = *in
	if in.Reviewer != nil {
		in, out := &in.Reviewer, &out.Reviewer
		*out = new(AgentReference)
		**out = **in
	}
	if in.Repairer != nil {
		in, out := &in.Repairer, &out.Repairer
		*out = new(AgentReference)
		**out = **in
	}
	if in.Implementer != nil {
		in, out := &in.Implementer, &out.Implementer
		*out = new(AgentReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMonitorAgents.
func (in *RepositoryMonitorAgents) DeepCopy() *RepositoryMonitorAgents {
	if in == nil {
		return nil
	}
	out := new(RepositoryMonitorAgents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMonitorAutomergeSpec) DeepCopyInto(out *RepositoryMonitorAutomergeSpec) {
	*out = *in
	if in.RequireMaintainerOptIn != nil {
		in, out := &in.RequireMaintainerOptIn, &out.RequireMaintainerOptIn
		*out = new(bool)
		**out = **in
	}
	if in.RequireGlobalMergeGate != nil {
		in, out := &in.RequireGlobalMergeGate, &out.RequireGlobalMergeGate
		*out = new(bool)
		**out = **in
	}
	if in.AllowedMergeMethods != nil {
		in, out := &in.AllowedMergeMethods, &out.AllowedMergeMethods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMonitorAutomergeSpec.
func (in *RepositoryMonitorAutomergeSpec) DeepCopy() *RepositoryMonitorAutomergeSpec {
	if in == nil {
		return nil
	}
	out := new(RepositoryMonitorAutomergeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMonitorCommitTarget) DeepCopyInto(out *RepositoryMonitorCommitTarget) {
	*out = *in
	if in.MaxPerRun != nil {
		in, out := &in.MaxPerRun, &out.MaxPerRun
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMonitorCommitTarget.
func (in *RepositoryMonitorCommitTarget) DeepCopy() *RepositoryMonitorCommitTarget {
	if in == nil {
		return nil
	}
	out := new(RepositoryMonitorCommitTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMonitorIssueTarget) DeepCopyInto(out *RepositoryMonitorIssueTarget) {
	*out = *in
	if in.MaxPerRun != nil {
		in, out := &in.MaxPerRun, &out.MaxPerRun
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMonitorIssueTarget.
func (in *RepositoryMonitorIssueTarget) DeepCopy() *RepositoryMonitorIssueTarget {
	if in == nil {
		return nil
	}
	out := new(RepositoryMonitorIssueTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMonitorList) DeepCopyInto(out *RepositoryMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RepositoryMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMonitorList.
func (in *RepositoryMonitorList) DeepCopy() *RepositoryMonitorList {
	if in == nil {
		return nil
	}
	out := new(RepositoryMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMonitorOptInLabels) DeepCopyInto(out *RepositoryMonitorOptInLabels) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMonitorOptInLabels.
func (in *RepositoryMonitorOptInLabels) DeepCopy() *RepositoryMonitorOptInLabels {
	if in == nil {
		return nil
	}
	out := new(RepositoryMonitorOptInLabels)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMonitorPolicySpec) DeepCopyInto(out *RepositoryMonitorPolicySpec) {
	*out = *in
	if in.ProtectedLabels != nil {
		in, out := &in.ProtectedLabels, &out.ProtectedLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PauseLabels != nil {
		in, out := &in.PauseLabels, &out.PauseLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.OptInLabels = in.OptInLabels
	out.AdvisoryLabels = in.AdvisoryLabels
	if in.AllowedRepositoryPermissions != nil {
		in, out := &in.AllowedRepositoryPermissions, &out.AllowedRepositoryPermissions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMonitorPolicySpec.
func (in *RepositoryMonitorPolicySpec) DeepCopy() *RepositoryMonitorPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RepositoryMonitorPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMonitorPullRequestTarget) DeepCopyInto(out *RepositoryMonitorPullRequestTarget) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.MaxPerRun != nil {
		in, out := &in.MaxPerRun, &out.MaxPerRun
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMonitorPullRequestTarget.
func (in *RepositoryMonitorPullRequestTarget) DeepCopy() *RepositoryMonitorPullRequestTarget {
	if in == nil {
		return nil
	}
	out := new(RepositoryMonitorPullRequestTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMonitorRepairSpec) DeepCopyInto(out *RepositoryMonitorRepairSpec) {
	*out = *in
	if in.RequireMaintainerOptIn != nil {
		in, out := &in.RequireMaintainerOptIn, &out.RequireMaintainerOptIn
		*out = new(bool)
		**out = **in
	}
	if in.MaxRepairsPerPR != nil {
		in, out := &in.MaxRepairsPerPR, &out.MaxRepairsPerPR
		*out = new(int32)
		**out = **in
	}
	if in.MaxRepairsPerHead != nil {
		in, out := &in.MaxRepairsPerHead, &out.MaxRepairsPerHead
		*out = new(int32)
		**out = **in
	}
	if in.MaxValidationRetries != nil {
		in, out := &in.MaxValidationRetries, &out.MaxValidationRetries
		*out = new(int32)
		**out = **in
	}
	if in.MaxReviewFixRetries != nil {
		in, out := &in.MaxReviewFixRetries, &out.MaxReviewFixRetries
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMonitorRepairSpec.
func (in *RepositoryMonitorRepairSpec) DeepCopy() *RepositoryMonitorRepairSpec {
	if in == nil {
		return nil
	}
	out := new(RepositoryMonitorRepairSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMonitorReviewPublishInlineSpec) DeepCopyInto(out *RepositoryMonitorReviewPublishInlineSpec) {
	*out = *in
	if in.MaxComments != nil {
		in, out := &in.MaxComments, &out.MaxComments
		*out = new(int32)
		**out = **in
	}
	if in.OnlyChangedLines != nil {
		in, out := &in.OnlyChangedLines, &out.OnlyChangedLines
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMonitorReviewPublishInlineSpec.
func (in *RepositoryMonitorReviewPublishInlineSpec) DeepCopy() *RepositoryMonitorReviewPublishInlineSpec {
	if in == nil {
		return nil
	}
	out := new(RepositoryMonitorReviewPublishInlineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMonitorReviewPublishSpec) DeepCopyInto(out *RepositoryMonitorReviewPublishSpec) {
	*out = *in
	if in.PostPassed != nil {
		in, out := &in.PostPassed, &out.PostPassed
		*out = new(bool)
		**out = **in
	}
	if in.PostNeedsChanges != nil {
		in, out := &in.PostNeedsChanges, &out.PostNeedsChanges
		*out = new(bool)
		**out = **in
	}
	if in.PostNeedsHuman != nil {
		in, out := &in.PostNeedsHuman, &out.PostNeedsHuman
		*out = new(bool)
		**out = **in
	}
	in.Inline.DeepCopyInto(&out.Inline)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMonitorReviewPublishSpec.
func (in *RepositoryMonitorReviewPublishSpec) DeepCopy() *RepositoryMonitorReviewPublishSpec {
	if in == nil {
		return nil
	}
	out := new(RepositoryMonitorReviewPublishSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMonitorReviewSpec) DeepCopyInto(out *RepositoryMonitorReviewSpec) {
	*out = *in
	if in.StaleReviewTTL != nil {
		in, out := &in.StaleReviewTTL, &out.StaleReviewTTL
		*out = new(metav1.Duration)
		**out = **in
	}
	in.Publish.DeepCopyInto(&out.Publish)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMonitorReviewSpec.
func (in *RepositoryMonitorReviewSpec) DeepCopy() *RepositoryMonitorReviewSpec {
	if in == nil {
		return nil
	}
	out := new(RepositoryMonitorReviewSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMonitorSpec) DeepCopyInto(out *RepositoryMonitorSpec) {
	*out = *in
	if in.GitSecretRef != nil {
		in, out := &in.GitSecretRef, &out.GitSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
	if in.Suspend != nil {
		in, out := &in.Suspend, &out.Suspend
		*out = new(bool)
		**out = **in
	}
	in.Targets.DeepCopyInto(&out.Targets)
	in.Agents.DeepCopyInto(&out.Agents)
	in.Review.DeepCopyInto(&out.Review)
	in.Repair.DeepCopyInto(&out.Repair)
	in.Automerge.DeepCopyInto(&out.Automerge)
	in.Policy.DeepCopyInto(&out.Policy)
	in.Validation.DeepCopyInto(&out.Validation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMonitorSpec.
func (in *RepositoryMonitorSpec) DeepCopy() *RepositoryMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(RepositoryMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMonitorStatus) DeepCopyInto(out *RepositoryMonitorStatus) {
	*out = *in
	if in.LastRunTime != nil {
		in, out := &in.LastRunTime, &out.LastRunTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulRunTime != nil {
		in, out := &in.LastSuccessfulRunTime, &out.LastSuccessfulRunTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMonitorStatus.
func (in *RepositoryMonitorStatus) DeepCopy() *RepositoryMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(RepositoryMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMonitorTargets) DeepCopyInto(out *RepositoryMonitorTargets) {
	*out = *in
	in.PullRequests.DeepCopyInto(&out.PullRequests)
	in.Issues.DeepCopyInto(&out.Issues)
	in.Commits.DeepCopyInto(&out.Commits)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMonitorTargets.
func (in *RepositoryMonitorTargets) DeepCopy() *RepositoryMonitorTargets {
	if in == nil {
		return nil
	}
	out := new(RepositoryMonitorTargets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryMonitorValidationSpec) DeepCopyInto(out *RepositoryMonitorValidationSpec) {
	*out = *in
	if in.Commands != nil {
		in, out := &in.Commands, &out.Commands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryMonitorValidationSpec.
func (in *RepositoryMonitorValidationSpec) DeepCopy() *RepositoryMonitorValidationSpec {
	if in == nil {
		return nil
	}
	out := new(RepositoryMonitorValidationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryScan) DeepCopyInto(out *RepositoryScan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryScan.
func (in *RepositoryScan) DeepCopy() *RepositoryScan {
	if in == nil {
		return nil
	}
	out := new(RepositoryScan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryScan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryScanList) DeepCopyInto(out *RepositoryScanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RepositoryScan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryScanList.
func (in *RepositoryScanList) DeepCopy() *RepositoryScanList {
	if in == nil {
		return nil
	}
	out := new(RepositoryScanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryScanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryScanSpec) DeepCopyInto(out *RepositoryScanSpec) {
	*out = *in
	if in.GitSecretRef != nil {
		in, out := &in.GitSecretRef, &out.GitSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
	if in.HistoryDays != nil {
		in, out := &in.HistoryDays, &out.HistoryDays
		*out = new(int32)
		**out = **in
	}
	out.AnalysisAgentRef = in.AnalysisAgentRef
	if in.PatchAgentRef != nil {
		in, out := &in.PatchAgentRef, &out.PatchAgentRef
		*out = new(AgentReference)
		**out = **in
	}
	if in.MaxFindingsPerRun != nil {
		in, out := &in.MaxFindingsPerRun, &out.MaxFindingsPerRun
		*out = new(int32)
		**out = **in
	}
	if in.Suspend != nil {
		in, out := &in.Suspend, &out.Suspend
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryScanSpec.
func (in *RepositoryScanSpec) DeepCopy() *RepositoryScanSpec {
	if in == nil {
		return nil
	}
	out := new(RepositoryScanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryScanStatus) DeepCopyInto(out *RepositoryScanStatus) {
	*out = *in
	if in.LastScanAt != nil {
		in, out := &in.LastScanAt, &out.LastScanAt
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulScanAt != nil {
		in, out := &in.LastSuccessfulScanAt, &out.LastSuccessfulScanAt
		*out = (*in).DeepCopy()
	}
	out.FindingCounts = in.FindingCounts
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryScanStatus.
func (in *RepositoryScanStatus) DeepCopy() *RepositoryScanStatus {
	if in == nil {
		return nil
	}
	out := new(RepositoryScanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestedBy) DeepCopyInto(out *RequestedBy) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestedBy.
func (in *RequestedBy) DeepCopy() *RequestedBy {
	if in == nil {
		return nil
	}
	out := new(RequestedBy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResultReference) DeepCopyInto(out *ResultReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResultReference.
func (in *ResultReference) DeepCopy() *ResultReference {
	if in == nil {
		return nil
	}
	out := new(ResultReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryPolicy) DeepCopyInto(out *RetryPolicy) {
	*out = *in
	if in.InitialDelay != nil {
		in, out := &in.InitialDelay, &out.InitialDelay
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryPolicy.
func (in *RetryPolicy) DeepCopy() *RetryPolicy {
	if in == nil {
		return nil
	}
	out := new(RetryPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionConfig) DeepCopyInto(out *SessionConfig) {
	*out = *in
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionConfig.
func (in *SessionConfig) DeepCopy() *SessionConfig {
	if in == nil {
		return nil
	}
	out := new(SessionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionReference) DeepCopyInto(out *SessionReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionReference.
func (in *SessionReference) DeepCopy() *SessionReference {
	if in == nil {
		return nil
	}
	out := new(SessionReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Skill) DeepCopyInto(out *Skill) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Skill.
func (in *Skill) DeepCopy() *Skill {
	if in == nil {
		return nil
	}
	out := new(Skill)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Skill) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillContent) DeepCopyInto(out *SkillContent) {
	*out = *in
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillContent.
func (in *SkillContent) DeepCopy() *SkillContent {
	if in == nil {
		return nil
	}
	out := new(SkillContent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillList) DeepCopyInto(out *SkillList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Skill, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillList.
func (in *SkillList) DeepCopy() *SkillList {
	if in == nil {
		return nil
	}
	out := new(SkillList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SkillList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillReference) DeepCopyInto(out *SkillReference) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(ConfigMapKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillReference.
func (in *SkillReference) DeepCopy() *SkillReference {
	if in == nil {
		return nil
	}
	out := new(SkillReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillSource) DeepCopyInto(out *SkillSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillSource.
func (in *SkillSource) DeepCopy() *SkillSource {
	if in == nil {
		return nil
	}
	out := new(SkillSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillSpec) DeepCopyInto(out *SkillSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Content.DeepCopyInto(&out.Content)
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(SkillSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillSpec.
func (in *SkillSpec) DeepCopy() *SkillSpec {
	if in == nil {
		return nil
	}
	out := new(SkillSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkillStatus) DeepCopyInto(out *SkillStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkillStatus.
func (in *SkillStatus) DeepCopy() *SkillStatus {
	if in == nil {
		return nil
	}
	out := new(SkillStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubstrateActorPool) DeepCopyInto(out *SubstrateActorPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubstrateActorPool.
func (in *SubstrateActorPool) DeepCopy() *SubstrateActorPool {
	if in == nil {
		return nil
	}
	out := new(SubstrateActorPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubstrateActorPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubstrateActorPoolList) DeepCopyInto(out *SubstrateActorPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SubstrateActorPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubstrateActorPoolList.
func (in *SubstrateActorPoolList) DeepCopy() *SubstrateActorPoolList {
	if in == nil {
		return nil
	}
	out := new(SubstrateActorPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubstrateActorPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubstrateActorPoolReference) DeepCopyInto(out *SubstrateActorPoolReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubstrateActorPoolReference.
func (in *SubstrateActorPoolReference) DeepCopy() *SubstrateActorPoolReference {
	if in == nil {
		return nil
	}
	out := new(SubstrateActorPoolReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubstrateActorPoolSpec) DeepCopyInto(out *SubstrateActorPoolSpec) {
	*out = *in
	out.TemplateRef = in.TemplateRef
	if in.WorkerPoolRef != nil {
		in, out := &in.WorkerPoolRef, &out.WorkerPoolRef
		*out = new(WorkspaceTemplateReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubstrateActorPoolSpec.
func (in *SubstrateActorPoolSpec) DeepCopy() *SubstrateActorPoolSpec {
	if in == nil {
		return nil
	}
	out := new(SubstrateActorPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubstrateActorPoolStatus) DeepCopyInto(out *SubstrateActorPoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubstrateActorPoolStatus.
func (in *SubstrateActorPoolStatus) DeepCopy() *SubstrateActorPoolStatus {
	if in == nil {
		return nil
	}
	out := new(SubstrateActorPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubstrateMCPActor) DeepCopyInto(out *SubstrateMCPActor) {
	*out = *in
	out.TemplateRef = in.TemplateRef
	if in.PoolRef != nil {
		in, out := &in.PoolRef, &out.PoolRef
		*out = new(SubstrateActorPoolReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubstrateMCPActor.
func (in *SubstrateMCPActor) DeepCopy() *SubstrateMCPActor {
	if in == nil {
		return nil
	}
	out := new(SubstrateMCPActor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Task) DeepCopyInto(out *Task) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Task.
func (in *Task) DeepCopy() *Task {
	if in == nil {
		return nil
	}
	out := new(Task)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Task) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskList) DeepCopyInto(out *TaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Task, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskList.
func (in *TaskList) DeepCopy() *TaskList {
	if in == nil {
		return nil
	}
	out := new(TaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskSpec) DeepCopyInto(out *TaskSpec) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
	if in.RetryPolicy != nil {
		in, out := &in.RetryPolicy, &out.RetryPolicy
		*out = new(RetryPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.SessionRef != nil {
		in, out := &in.SessionRef, &out.SessionRef
		*out = new(SessionReference)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Execution != nil {
		in, out := &in.Execution, &out.Execution
		*out = new(ExecutionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
	if in.StartingDeadlineSeconds != nil {
		in, out := &in.StartingDeadlineSeconds, &out.StartingDeadlineSeconds
		*out = new(int64)
		**out = **in
	}
	if in.SuccessfulRunsHistoryLimit != nil {
		in, out := &in.SuccessfulRunsHistoryLimit, &out.SuccessfulRunsHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.FailedRunsHistoryLimit != nil {
		in, out := &in.FailedRunsHistoryLimit, &out.FailedRunsHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.Suspend != nil {
		in, out := &in.Suspend, &out.Suspend
		*out = new(bool)
		**out = **in
	}
	if in.AI != nil {
		in, out := &in.AI, &out.AI
		*out = new(AISpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AgentRef != nil {
		in, out := &in.AgentRef, &out.AgentRef
		*out = new(AgentReference)
		**out = **in
	}
	if in.AgentRuntime != nil {
		in, out := &in.AgentRuntime, &out.AgentRuntime
		*out = new(AgentRuntimeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Workspace != nil {
		in, out := &in.Workspace, &out.Workspace
		*out = new(WorkspaceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PriorTaskRef != nil {
		in, out := &in.PriorTaskRef, &out.PriorTaskRef
		*out = new(PriorTaskReference)
		**out = **in
	}
	if in.RequestedBy != nil {
		in, out := &in.RequestedBy, &out.RequestedBy
		*out = new(RequestedBy)
		(*in).DeepCopyInto(*out)
	}
	if in.Transaction != nil {
		in, out := &in.Transaction, &out.Transaction
		*out = new(TaskTransaction)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskSpec.
func (in *TaskSpec) DeepCopy() *TaskSpec {
	if in == nil {
		return nil
	}
	out := new(TaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskStatus) DeepCopyInto(out *TaskStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.ResultRef != nil {
		in, out := &in.ResultRef, &out.ResultRef
		*out = new(ResultReference)
		**out = **in
	}
	if in.ExecutionWorkspace != nil {
		in, out := &in.ExecutionWorkspace, &out.ExecutionWorkspace
		*out = new(ExecutionWorkspaceStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ChildTasks != nil {
		in, out := &in.ChildTasks, &out.ChildTasks
		*out = make([]ChildTaskStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastScheduleTime != nil {
		in, out := &in.LastScheduleTime, &out.LastScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.NextScheduleTime != nil {
		in, out := &in.NextScheduleTime, &out.NextScheduleTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskStatus.
func (in *TaskStatus) DeepCopy() *TaskStatus {
	if in == nil {
		return nil
	}
	out := new(TaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskTransaction) DeepCopyInto(out *TaskTransaction) {
	*out = *in
	if in.Audience != nil {
		in, out := &in.Audience, &out.Audience
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Context != nil {
		in, out := &in.Context, &out.Context
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskTransaction.
func (in *TaskTransaction) DeepCopy() *TaskTransaction {
	if in == nil {
		return nil
	}
	out := new(TaskTransaction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tool) DeepCopyInto(out *Tool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tool.
func (in *Tool) DeepCopy() *Tool {
	if in == nil {
		return nil
	}
	out := new(Tool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolActorStatus) DeepCopyInto(out *ToolActorStatus) {
	*out = *in
	if in.TemplateRef != nil {
		in, out := &in.TemplateRef, &out.TemplateRef
		*out = new(WorkspaceTemplateReference)
		**out = **in
	}
	if in.PoolRef != nil {
		in, out := &in.PoolRef, &out.PoolRef
		*out = new(SubstrateActorPoolReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolActorStatus.
func (in *ToolActorStatus) DeepCopy() *ToolActorStatus {
	if in == nil {
		return nil
	}
	out := new(ToolActorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolList) DeepCopyInto(out *ToolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolList.
func (in *ToolList) DeepCopy() *ToolList {
	if in == nil {
		return nil
	}
	out := new(ToolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ToolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolReference) DeepCopyInto(out *ToolReference) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolReference.
func (in *ToolReference) DeepCopy() *ToolReference {
	if in == nil {
		return nil
	}
	out := new(ToolReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolSpec) DeepCopyInto(out *ToolSpec) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPExecution)
		(*in).DeepCopyInto(*out)
	}
	if in.MCP != nil {
		in, out := &in.MCP, &out.MCP
		*out = new(MCPToolServer)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolSpec.
func (in *ToolSpec) DeepCopy() *ToolSpec {
	if in == nil {
		return nil
	}
	out := new(ToolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolStatus) DeepCopyInto(out *ToolStatus) {
	*out = *in
	if in.LastCheck != nil {
		in, out := &in.LastCheck, &out.LastCheck
		*out = (*in).DeepCopy()
	}
	if in.Actor != nil {
		in, out := &in.Actor, &out.Actor
		*out = new(ToolActorStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolStatus.
func (in *ToolStatus) DeepCopy() *ToolStatus {
	if in == nil {
		return nil
	}
	out := new(ToolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceConfig) DeepCopyInto(out *WorkspaceConfig) {
	*out = *in
	if in.GitSecretRef != nil {
		in, out := &in.GitSecretRef, &out.GitSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceConfig.
func (in *WorkspaceConfig) DeepCopy() *WorkspaceConfig {
	if in == nil {
		return nil
	}
	out := new(WorkspaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceTemplateReference) DeepCopyInto(out *WorkspaceTemplateReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceTemplateReference.
func (in *WorkspaceTemplateReference) DeepCopy() *WorkspaceTemplateReference {
	if in == nil {
		return nil
	}
	out := new(WorkspaceTemplateReference)
	in.DeepCopyInto(out)
	return out
}
