apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# `harness-wrapper-auth` must be pre-created; see README.md.
resources:
- serviceaccount.yaml
- deployment.yaml
- service.yaml

patches:
- path: volume-mode-patch.yaml
