//go:build !ignore_autogenerated

/*
Copyright (c) 2026.

MIT License - see LICENSE file for details.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Gateway) DeepCopyInto(out *Gateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Gateway.
func (in *Gateway) DeepCopy() *Gateway {
	if in == nil {
		return nil
	}
	out := new(Gateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Gateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayAdapterLocation) DeepCopyInto(out *GatewayAdapterLocation) {
	*out = *in
	if in.ServiceRef != nil {
		in, out := &in.ServiceRef, &out.ServiceRef
		*out = new(GatewayServiceReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayAdapterLocation.
func (in *GatewayAdapterLocation) DeepCopy() *GatewayAdapterLocation {
	if in == nil {
		return nil
	}
	out := new(GatewayAdapterLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayBearerAuthReference) DeepCopyInto(out *GatewayBearerAuthReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayBearerAuthReference.
func (in *GatewayBearerAuthReference) DeepCopy() *GatewayBearerAuthReference {
	if in == nil {
		return nil
	}
	out := new(GatewayBearerAuthReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayBinding) DeepCopyInto(out *GatewayBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayBinding.
func (in *GatewayBinding) DeepCopy() *GatewayBinding {
	if in == nil {
		return nil
	}
	out := new(GatewayBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayBindingList) DeepCopyInto(out *GatewayBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GatewayBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayBindingList.
func (in *GatewayBindingList) DeepCopy() *GatewayBindingList {
	if in == nil {
		return nil
	}
	out := new(GatewayBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayBindingMatch) DeepCopyInto(out *GatewayBindingMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayBindingMatch.
func (in *GatewayBindingMatch) DeepCopy() *GatewayBindingMatch {
	if in == nil {
		return nil
	}
	out := new(GatewayBindingMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayBindingReference) DeepCopyInto(out *GatewayBindingReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayBindingReference.
func (in *GatewayBindingReference) DeepCopy() *GatewayBindingReference {
	if in == nil {
		return nil
	}
	out := new(GatewayBindingReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayBindingSpec) DeepCopyInto(out *GatewayBindingSpec) {
	*out = *in
	out.GatewayRef = in.GatewayRef
	out.AgentRef = in.AgentRef
	out.Match = in.Match
	in.SenderPolicy.DeepCopyInto(&out.SenderPolicy)
	out.Session = in.Session
	in.TaskDefaults.DeepCopyInto(&out.TaskDefaults)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayBindingSpec.
func (in *GatewayBindingSpec) DeepCopy() *GatewayBindingSpec {
	if in == nil {
		return nil
	}
	out := new(GatewayBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayBindingStatus) DeepCopyInto(out *GatewayBindingStatus) {
	*out = *in
	if in.ResolvedCapabilities != nil {
		in, out := &in.ResolvedCapabilities, &out.ResolvedCapabilities
		*out = new(GatewayCapabilities)
		**out = **in
	}
	if in.LastInboundActivity != nil {
		in, out := &in.LastInboundActivity, &out.LastInboundActivity
		*out = (*in).DeepCopy()
	}
	if in.LastOutboundActivity != nil {
		in, out := &in.LastOutboundActivity, &out.LastOutboundActivity
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayBindingStatus.
func (in *GatewayBindingStatus) DeepCopy() *GatewayBindingStatus {
	if in == nil {
		return nil
	}
	out := new(GatewayBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayCapabilities) DeepCopyInto(out *GatewayCapabilities) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayCapabilities.
func (in *GatewayCapabilities) DeepCopy() *GatewayCapabilities {
	if in == nil {
		return nil
	}
	out := new(GatewayCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayClass) DeepCopyInto(out *GatewayClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayClass.
func (in *GatewayClass) DeepCopy() *GatewayClass {
	if in == nil {
		return nil
	}
	out := new(GatewayClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayClassList) DeepCopyInto(out *GatewayClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GatewayClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayClassList.
func (in *GatewayClassList) DeepCopy() *GatewayClassList {
	if in == nil {
		return nil
	}
	out := new(GatewayClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayClassSpec) DeepCopyInto(out *GatewayClassSpec) {
	*out = *in
	out.Capabilities = in.Capabilities
	if in.AllowedMetadataKeys != nil {
		in, out := &in.AllowedMetadataKeys, &out.AllowedMetadataKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayClassSpec.
func (in *GatewayClassSpec) DeepCopy() *GatewayClassSpec {
	if in == nil {
		return nil
	}
	out := new(GatewayClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayClassStatus) DeepCopyInto(out *GatewayClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayClassStatus.
func (in *GatewayClassStatus) DeepCopy() *GatewayClassStatus {
	if in == nil {
		return nil
	}
	out := new(GatewayClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayList) DeepCopyInto(out *GatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Gateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayList.
func (in *GatewayList) DeepCopy() *GatewayList {
	if in == nil {
		return nil
	}
	out := new(GatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayObservedCapabilities) DeepCopyInto(out *GatewayObservedCapabilities) {
	*out = *in
	out.Capabilities = in.Capabilities
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayObservedCapabilities.
func (in *GatewayObservedCapabilities) DeepCopy() *GatewayObservedCapabilities {
	if in == nil {
		return nil
	}
	out := new(GatewayObservedCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaySenderPolicy) DeepCopyInto(out *GatewaySenderPolicy) {
	*out = *in
	if in.AllowedSenderIDs != nil {
		in, out := &in.AllowedSenderIDs, &out.AllowedSenderIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySenderPolicy.
func (in *GatewaySenderPolicy) DeepCopy() *GatewaySenderPolicy {
	if in == nil {
		return nil
	}
	out := new(GatewaySenderPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayServiceReference) DeepCopyInto(out *GatewayServiceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayServiceReference.
func (in *GatewayServiceReference) DeepCopy() *GatewayServiceReference {
	if in == nil {
		return nil
	}
	out := new(GatewayServiceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaySessionSpec) DeepCopyInto(out *GatewaySessionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySessionSpec.
func (in *GatewaySessionSpec) DeepCopy() *GatewaySessionSpec {
	if in == nil {
		return nil
	}
	out := new(GatewaySessionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaySpec) DeepCopyInto(out *GatewaySpec) {
	*out = *in
	in.Adapter.DeepCopyInto(&out.Adapter)
	out.InboundAuthRef = in.InboundAuthRef
	out.OutboundAuthRef = in.OutboundAuthRef
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySpec.
func (in *GatewaySpec) DeepCopy() *GatewaySpec {
	if in == nil {
		return nil
	}
	out := new(GatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayStatus) DeepCopyInto(out *GatewayStatus) {
	*out = *in
	if in.ObservedCapabilities != nil {
		in, out := &in.ObservedCapabilities, &out.ObservedCapabilities
		*out = new(GatewayObservedCapabilities)
		**out = **in
	}
	if in.LastSuccessfulProbe != nil {
		in, out := &in.LastSuccessfulProbe, &out.LastSuccessfulProbe
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayStatus.
func (in *GatewayStatus) DeepCopy() *GatewayStatus {
	if in == nil {
		return nil
	}
	out := new(GatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayTaskDefaults) DeepCopyInto(out *GatewayTaskDefaults) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.RetryPolicy != nil {
		in, out := &in.RetryPolicy, &out.RetryPolicy
		*out = new(GatewayTaskRetryPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.AgentRuntimeMaxTurns != nil {
		in, out := &in.AgentRuntimeMaxTurns, &out.AgentRuntimeMaxTurns
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayTaskDefaults.
func (in *GatewayTaskDefaults) DeepCopy() *GatewayTaskDefaults {
	if in == nil {
		return nil
	}
	out := new(GatewayTaskDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayTaskRetryPolicy) DeepCopyInto(out *GatewayTaskRetryPolicy) {
	*out = *in
	if in.InitialDelay != nil {
		in, out := &in.InitialDelay, &out.InitialDelay
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayTaskRetryPolicy.
func (in *GatewayTaskRetryPolicy) DeepCopy() *GatewayTaskRetryPolicy {
	if in == nil {
		return nil
	}
	out := new(GatewayTaskRetryPolicy)
	in.DeepCopyInto(out)
	return out
}
