#!/usr/bin/env bash
set -Eeuo pipefail

usage() {
  echo "Usage: $0 OUTPUT_DIR CODEX_IMAGE CLAUDE_IMAGE COPILOT_IMAGE OPENCODE_IMAGE" >&2
}

[[ $# -eq 5 ]] || {
  usage
  exit 2
}

output_dir="$1"
codex_image="$2"
claude_image="$3"
copilot_image="$4"
opencode_image="$5"

[[ -d "${output_dir}" && ! -L "${output_dir}" ]] || {
  echo "ACP production output directory must be a real directory: ${output_dir}" >&2
  exit 1
}

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
command -v go >/dev/null 2>&1 || {
  echo "Go is required to validate ACP runtime image references" >&2
  exit 1
}
if ! (cd "${root}" && go run ./cmd/orka-image-ref-validator "${codex_image}" "${claude_image}" "${copilot_image}" "${opencode_image}"); then
  echo "ACP runtime image reference validation failed" >&2
  exit 1
fi

env_tmp="$(mktemp "${output_dir}/.runtime-images.XXXXXX")"
cleanup() {
  rm -f -- "${env_tmp}"
}
trap cleanup EXIT

cat >"${env_tmp}" <<EOF_ENV
# Generated by scripts/render-acp-runtime-images.sh. Kustomize hashes this
# complete generation and rewrites the controller Deployment reference.
ORKA_ACP_CODEX_RUNTIME_IMAGE=${codex_image}
ORKA_ACP_CLAUDE_RUNTIME_IMAGE=${claude_image}
ORKA_ACP_COPILOT_RUNTIME_IMAGE=${copilot_image}
ORKA_ACP_OPENCODE_RUNTIME_IMAGE=${opencode_image}
EOF_ENV

mv -f -- "${env_tmp}" "${output_dir}/runtime-images.env"
