# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/core.orka.ai_tasks.yaml
- bases/core.orka.ai_tools.yaml
- bases/core.orka.ai_agents.yaml
- bases/core.orka.ai_agentruntimes.yaml
- bases/core.orka.ai_providers.yaml
- bases/core.orka.ai_skills.yaml
- bases/core.orka.ai_repositoryscans.yaml
- bases/core.orka.ai_repositorymonitors.yaml
- bases/core.orka.ai_substrateactorpools.yaml
- bases/core.orka.ai_outboundaccesspolicies.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch
