{{- include "orka.validateAdmission" . }}
{{- if .Values.admission.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orka.admissionName" . }}
  labels:
    {{- include "orka.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission
spec:
  selector:
    {{- include "orka.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: admission
  ports:
    - name: https
      port: 443
      targetPort: webhook
      protocol: TCP
{{- end }}
