apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-auth-proxy
  labels:
    app.kubernetes.io/name: orka
    app.kubernetes.io/component: provider-auth-proxy
automountServiceAccountToken: false
