//go:build !ignore_autogenerated

/*
Copyright (c) 2026.

MIT License - see LICENSE file for details.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeProviderConfig) DeepCopyInto(out *RuntimeProviderConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeProviderConfig.
func (in *RuntimeProviderConfig) DeepCopy() *RuntimeProviderConfig {
	if in == nil {
		return nil
	}
	out := new(RuntimeProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuntimeProviderConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeProviderConfigList) DeepCopyInto(out *RuntimeProviderConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RuntimeProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeProviderConfigList.
func (in *RuntimeProviderConfigList) DeepCopy() *RuntimeProviderConfigList {
	if in == nil {
		return nil
	}
	out := new(RuntimeProviderConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuntimeProviderConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeProviderConfigSpec) DeepCopyInto(out *RuntimeProviderConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeProviderConfigSpec.
func (in *RuntimeProviderConfigSpec) DeepCopy() *RuntimeProviderConfigSpec {
	if in == nil {
		return nil
	}
	out := new(RuntimeProviderConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeWorkspaceProfile) DeepCopyInto(out *RuntimeWorkspaceProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeWorkspaceProfile.
func (in *RuntimeWorkspaceProfile) DeepCopy() *RuntimeWorkspaceProfile {
	if in == nil {
		return nil
	}
	out := new(RuntimeWorkspaceProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuntimeWorkspaceProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeWorkspaceProfileList) DeepCopyInto(out *RuntimeWorkspaceProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RuntimeWorkspaceProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeWorkspaceProfileList.
func (in *RuntimeWorkspaceProfileList) DeepCopy() *RuntimeWorkspaceProfileList {
	if in == nil {
		return nil
	}
	out := new(RuntimeWorkspaceProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuntimeWorkspaceProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeWorkspaceProfileSpec) DeepCopyInto(out *RuntimeWorkspaceProfileSpec) {
	*out = *in
	if in.Substrate != nil {
		in, out := &in.Substrate, &out.Substrate
		*out = new(SubstrateProfileSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeWorkspaceProfileSpec.
func (in *RuntimeWorkspaceProfileSpec) DeepCopy() *RuntimeWorkspaceProfileSpec {
	if in == nil {
		return nil
	}
	out := new(RuntimeWorkspaceProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubstrateProfileSpec) DeepCopyInto(out *SubstrateProfileSpec) {
	*out = *in
	out.TemplateRef = in.TemplateRef
	if in.Suspend != nil {
		in, out := &in.Suspend, &out.Suspend
		*out = new(SubstrateSuspendPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubstrateProfileSpec.
func (in *SubstrateProfileSpec) DeepCopy() *SubstrateProfileSpec {
	if in == nil {
		return nil
	}
	out := new(SubstrateProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubstrateSuspendPolicy) DeepCopyInto(out *SubstrateSuspendPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubstrateSuspendPolicy.
func (in *SubstrateSuspendPolicy) DeepCopy() *SubstrateSuspendPolicy {
	if in == nil {
		return nil
	}
	out := new(SubstrateSuspendPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubstrateTemplateReference) DeepCopyInto(out *SubstrateTemplateReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubstrateTemplateReference.
func (in *SubstrateTemplateReference) DeepCopy() *SubstrateTemplateReference {
	if in == nil {
		return nil
	}
	out := new(SubstrateTemplateReference)
	in.DeepCopyInto(out)
	return out
}
