apiVersion: v1
kind: ServiceAccount
metadata:
  name: scm-egress-proxy
  labels:
    app.kubernetes.io/name: orka
    app.kubernetes.io/component: scm-egress-proxy
automountServiceAccountToken: false
